name: Build SH1MMER
on:
  workflow_dispatch:
    inputs:
      board:
        default: 'kefka'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building ${{ github.event.inputs.board }}"



